AllCops:
  TargetRubyVersion: 2.4.1
  TargetRailsVersion: 5.2

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FormatString:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
